#!/usr/bin/env bash


# Copyright (c) 2023 Sławek Wernikowski slawern@gmail.com

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

#
# mkbk - simple backup tool
# makes a backup of specified files under name:
#
#   source_file_name.YYMMDDhhmmss
#
# usage: mkbk source_file... [ destination_dir ]
#
# if no destination dir is specified, backups are created inside current directory
#

usage(){
    >&2 echo "Usage: " `basename $0` "file... [destination_dir]"
    exit 1
}

argc=$#
if [ $argc -eq 0 ]
then
    usage
fi
last_arg=${@: -1}
dest_dir="./"
if [ -d "$last_arg" ]
then
    dest_dir="$last_arg/"
    argc=$((argc-1))
fi
if [ $argc -eq 0 ]
then
    usage
fi
if [ -w "$dest_dir" ]
then
    echo "Destination dir is not writable"
    exit 2
fi
time_str=`date +%y%m%d%H%M%S`
for((i = 0; i < $argc; i++))
do
    src_name=$1
    shift
    if [ ! -f $name ]
    then
        >&2 echo "$name does not exist or is not a regular file - ignored"
        continue
    fi
    trg_name="$dest_dir$src_name.$time_str"
    cp -v $src_name $trg_name
done
