#!/usr/bin/env bash


usage(){
    >&2 echo "Usage: " `basename $0` "file... [dir]"
    exit 1
}

argc=$#
if [ $argc -eq 0 ]
then
    usage
fi
last_arg=${@: -1}
dest_dir="./"
if [ -d "$last_arg" ]
then
    dest_dir="$last_arg/"
    argc=$((argc-1))
fi
if [ $argc -eq 0 ]
then
    usage
fi
if [ -w "$dest_dir" ]
then
    echo "Destination dir is not writable"
    exit 2
fi
time_str=`date +%y%m%d%H%M%S`
for((i = 0; i < $argc; i++))
do
    src_name=$1
    shift
    if [ ! -f $name ]
    then
        >&2 echo "$name does not exist or is not a regular file - ignored"
        continue
    fi
    trg_name="$dest_dir$src_name.$time_str"
    cp -v $src_name $trg_name
done
